// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: feed_follows_delete.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteSpecificFeedFollows = `-- name: DeleteSpecificFeedFollows :exec
DELETE FROM feed_follows WHERE id = $1 AND user_id = $2
`

type DeleteSpecificFeedFollowsParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSpecificFeedFollows(ctx context.Context, arg DeleteSpecificFeedFollowsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpecificFeedFollows, arg.ID, arg.UserID)
	return err
}
