// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users_apikey_get.sql

package database

import (
	"context"
)

const aPIKeyGetUser = `-- name: APIKeyGetUser :one
SELECT id, created_at, updated_at, name, api_key FROM users WHERE api_key = $1
`

func (q *Queries) APIKeyGetUser(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, aPIKeyGetUser, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ApiKey,
	)
	return i, err
}
